@protocol = http 
@hostname = localhost
@port = 3000
@host = {{protocol}}://{{hostname}}:{{port}}
@urlPrefix = /api
@contentType = application/json
@username = admin
@password = password
@serviceVersion = 1
@apiVersion = 1
@userId = 1
@workspaceId = 1

###
# Get Hello World
GET {{host}}{{urlPrefix}} HTTP/1.1
# GET {{host}}{{urlPrefix}}
Accept: {{contentType}}
