version: '3.9'
    
services:
  calendar-srv:
    user: "node"
    env_file:
      - ../env/development.env
    build: .
    working_dir: /home/node/workspace/
    ports:
      - 3003:3003
    volumes:
      - ~/.ssh:/home/node/.ssh
      - ..:/home/node/workspace/
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    hostname: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: calendar_v1
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password