version: '3.9'
    
services:
  calendar-srv:
    user: "node"
    build: .
    working_dir: /home/node/workspace/
    ports:
      - 3000:3000
    volumes:
      - ~/.ssh:/home/node/.ssh
      - ..:/home/node/workspace/